version: '3.8'
services:
  server:
    image: bitnami/laravel:9
    volumes:
      - ./server:/app
    environment: 
      - LARAVEL_DATABASE_HOST=database
      - LARAVEL_DATABASE_NAME=editor
      - LARAVEL_DATABASE_USER=root
      - LARAVEL_DATABASE_PASSWORD=sef61
      - LARAVEL_DATABASE_PORT_NUMBER=3306
    restart: always
    ports:
      - "80:8000" 
    depends_on:
      - database
    command: >
      sh -c "while ! nc -z database 3306; do sleep 1; done &&
      php artisan migrate --force &&
      php artisan serve --host=0.0.0.0 --port=8000"
  database:
    image: mysql:8.0
    environment:
     - MYSQL_ROOT_PASSWORD=sef61
     - MYSQL_DATABASE=editor
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 10

    
volumes:
  db-data: