services:
  server:
    image: bitnami/laravel
    volumes:
      -./server:/app
    environment: 
      - LARAVEL_DATABASE_HOST= database
      - LARAVEL_DATABASE_NAME= editor
      - LARAVEL_DATABASE_USER=root
      - LARAVEL_DATABASE_PASSWORD=sef61
      - LARAVEL_DATABASE_PORT_NUMBER=3306
    retart: always
    ports:
      - 8000:8000  
    command: ./shell
  database:
    image: mysql:8.0
    environment:
     - MYSQL_ROOT_PASSWORD = sef61
     - MYSQL_DATABASE= editor