name: Push and Deploy

on:
  push:
    branches:
      - main
jobs:
  Deploy-Laravel-EC2:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy on EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_key }}
          script: |
            git pull origin main
            docker-compose down
            docker rmi ${{ secrets.DOCKER_USERNAME }}/image-editor:latest
            docker-compose up -d
      
