name: Push and Deploy

on:
  push:
    branches:
      - main
jobs:
  Build-And-Push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
        
      - name: Build Laravel Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/image-editor:latest .

      - name: Push Docker image 
        run: docker push ${{ secrets.DOCKER_USERNAME }}/image-editor:latest

  Deploy-Laravel-Docker:
    needs: Build-And-Push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy on EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_key }}
          script: |
            git pull origin main
            docker-compose down
            docker rmi ${{ secrets.DOCKER_USERNAME }}/image-editor:latest
            docker-compose up -d
      
